mergetool learned "memorize patch"

diff --git a/flmergetool b/flmergetool
--- a/flmergetool
+++ b/flmergetool
@@ -72,17 +72,29 @@ for file1 in "$BASE" "$LOCAL" "$REMOTE"; do
             #echo "FLScriptParse OK" 
             is_done=0
         else
-            read -p "Fallo en el parseo del fichero, desea abrir un editor para corregirlo manualmente? [Y/n]:" editor
-            [[ $editor == "n" ]] && {
-            echo "FLScriptParse FAILED"
-            exit 1
-            }
-            [[ $editor ]] || editor="medit"
-            [[ $editor == "Y" ]] || editor="medit"
-            [[ $editor == "y" ]] || editor="medit"
-            "$editor" "$file1"
-            read -p "Pulse Intro si ha terminado." 
-        
+            patched=0
+            for kpatch in /tmp/knownpatch.*; do
+                [[ $kpatch == "/tmp/knownpatch.*" ]] && break
+                patch "$file1" "$kpatch" -f -F4 -l && {
+                    patched=1
+                }
+            done
+            if [[ $patched == 0 ]]; then
+                read -p "Fallo en el parseo del fichero, desea abrir un editor para corregirlo manualmente? [Y/n]:" editor
+                [[ $editor == "n" ]] && {
+                echo "FLScriptParse FAILED"
+                exit 1
+                }
+                bname=$(basename "$file1")
+                [[ $editor ]] || editor="medit"
+                [[ $editor == "Y" ]] || editor="medit"
+                [[ $editor == "y" ]] || editor="medit"
+                cp $file1 /tmp/$bname.orig
+                "$editor" "$file1"
+                read -p "Pulse Intro si ha terminado." 
+                diff -U6 -p --minimal -d /tmp/$bname.orig $file1 >/tmp/knownpatch.$bname.patch.tmp && \
+                    mv /tmp/knownpatch.$bname.patch.tmp /tmp/knownpatch.$bname.patch
+            fi        
         fi
     done
 done
