More and more bug fixes

diff --git a/flmergetool b/flmergetool
--- a/flmergetool
+++ b/flmergetool
@@ -14,6 +14,12 @@ then
     git config --global mergetool.flmergetool.trustExitCode true
     exit 0
 fi
+if [[ $1 == "--debug" ]]; then
+    DEBUG="--debug"
+    shift
+else
+    DEBUG=""
+fi
 MERGE=$1
 BASE=$2
 LOCAL=$4
@@ -81,15 +87,8 @@ for file1 in "$BASE" "$LOCAL" "$REMOTE"; do
     done
 done
 
-if test -f $BASE && test -f $LOCAL && test -f $REMOTE
-then
-    OK=1
-else
-    echo "FLScriptParse FAILED"
-    exit 1
-fi
     
-if python $thisdir/flpremerge.py $BASE $LOCAL $REMOTE 
+if python $thisdir/flpremerge.py $DEBUG $BASE $LOCAL $REMOTE 
 then
     #echo "FLPreMerge OK"
     OK=1
@@ -98,7 +97,7 @@ else
     exit 1
 fi
 
-if python $thisdir/flalign.py $BASE $LOCAL $REMOTE 
+if python $thisdir/flalign.py $DEBUG $BASE $LOCAL $REMOTE 
 then
     #echo "FLAlign OK"
     OK=1
@@ -106,8 +105,17 @@ else
     echo "FLAlign FAILED"
     exit 1
 fi
+
+if test -f $BASE.aligned && test -f $LOCAL.aligned && test -f $REMOTE.aligned
+then
+    OK=1
+else
+    echo "FLAlign FAILED"
+    exit 1
+fi
+unlink $MERGE
 #echo "kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto"
-if kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto >/dev/null 2>&1
+if kdiff3 --auto $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE >/dev/null 2>&1
 then
     #echo "KDIFF3 OK"
     OK=1
