Bug corrections to mergetool

diff --git a/flmergetool b/flmergetool
--- a/flmergetool
+++ b/flmergetool
@@ -26,20 +26,27 @@ else
     exit 1
 fi
 
-if test -f $BASE 
-then
-    OK=1
-else
-    echo "File $BASE does not exist."
-    exit 1
-fi
-
 if test -f $REMOTE
 then
     OK=1
 else
     echo "File $REMOTE does not exist."
     exit 1
+fi
+
+if test -f $BASE 
+then
+    OK=1
+else
+    if kdiff3 $LOCAL $REMOTE -o $MERGE >/dev/null 2>&1
+    then
+        #echo "KDIFF3 OK"
+        OK=1
+        exit 0
+    else
+        echo "KDIFF3 FAILED"
+        exit 1
+    fi
 fi
 
 if echo $MERGE | grep -E '\.qs' 
@@ -56,7 +63,7 @@ for file1 in "$BASE" "$LOCAL" "$REMOTE"; do
     do
         if python $thisdir/flscriptparse.py -O file "$file1" && test -f "$file1.xml"
         then
-            echo "FLScriptParse OK" 
+            #echo "FLScriptParse OK" 
             is_done=0
         else
             read -p "Fallo en el parseo del fichero, desea abrir un editor para corregirlo manualmente? [Y/n]:" editor
@@ -84,7 +91,8 @@ fi
     
 if python $thisdir/flpremerge.py $BASE $LOCAL $REMOTE 
 then
-    echo "FLPreMerge OK"
+    #echo "FLPreMerge OK"
+    OK=1
 else
     echo "FLPreMerge FAILED"
     exit 1
@@ -92,15 +100,17 @@ fi
 
 if python $thisdir/flalign.py $BASE $LOCAL $REMOTE 
 then
-    echo "FLAlign OK"
+    #echo "FLAlign OK"
+    OK=1
 else
     echo "FLAlign FAILED"
     exit 1
 fi
-echo "kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto"
-if kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto
+#echo "kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto"
+if kdiff3 $BASE.aligned $LOCAL.aligned $REMOTE.aligned -o $MERGE --auto >/dev/null 2>&1
 then
-    echo "KDIFF3 OK"
+    #echo "KDIFF3 OK"
+    OK=1
 else
     echo "KDIFF3 FAILED"
     exit 1
